# Generated by Django 3.0.7 on 2020-10-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='height',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='width',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='x',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='y',
        ),
        migrations.AddField(
            model_name='profile',
            name='binary',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
