# Generated by Django 3.0.7 on 2020-10-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='old_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
