# Generated by Django 3.0.7 on 2020-10-07 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201008_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='binary',
        ),
    ]
