# Generated by Django 3.0.7 on 2020-10-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_binary'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='left',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='lower',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='right',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='upper',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
