# Generated by Django 3.0.7 on 2020-10-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201008_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='orientation',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
