# Generated by Django 3.0.7 on 2020-10-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_profile_orientation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image_path_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
