# Generated by Django 3.0.7 on 2020-08-31 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Photos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='author_id',
            new_name='author',
        ),
    ]
