# Generated by Django 3.0.7 on 2020-10-10 07:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='meta',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='photo',
            name='date_taken',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
