# Generated by Django 3.0.7 on 2020-08-31 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Photos', '0004_auto_20200831_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True, default='Description'),
        ),
    ]
