# Generated by Django 3.0.7 on 2020-09-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Photos', '0005_auto_20200831_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo2',
            name='date_taken',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
