# Generated by Django 3.0.7 on 2020-09-06 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Photos', '0006_auto_20200906_0040'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo2',
        ),
    ]
