# Generated by Django 3.0.7 on 2020-09-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Photos', '0008_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='title',
            field=models.CharField(blank=True, default='Title', max_length=100, null=True),
        ),
    ]
