# Generated by Django 3.0.7 on 2020-09-16 15:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Photos', '0009_photo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
