# Generated by Django 3.0.7 on 2020-09-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Photos', '0010_comments_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True, default='Описание'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(blank=True, default='Заголовок', max_length=100, null=True),
        ),
    ]
